### ISSUE TITLE
Navbar text overflow when table name is too long

### ISSUE THREAD

**Issue by esyede** [febryars33/eyed-phpmyadmin-theme#4]
Sample:
![Image](https://github.com/user-attachments/assets/2ba53100-cf69-40fd-838e-e8eb81b6cfca)

Fixes:

```css
li.nav_node_table.nav_node_table {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

Result:

![Image](https://github.com/user-attachments/assets/f79a90d2-300a-40c8-b5dd-2c6b5e5279b0)
